image: alpine:latest

pages:
  script:
    - mkdir .public
    - cp -r * .public
    - https://www.offargu.com/*  https://offargu.com/:splat  301!
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main